export const Locations = [
  {
    group: 'Metro',
    items: [
      'Alsancak',
      'Basmane',
      'Şirinyer',
      'Evka 3',
      'Evka 4',
      'Kayaşehri',
      'Bornova',
      'Halkapınar',
      'Uçak',
      'Çankaya',
      'Halkapınar',
      'Hilal',
      'Göztepe',
      'İzmirspor',
    ],
  },
  {
    group: 'İzban',
    items: [
      'Cumaovası',
      'Menemen',
      'Alsancak',
      'Sasalı',
      'İzmirspor',
      'Hilal',
      'Göztepe',
      'Basmane',
      'Çankaya',
      'Uçak',
      'Halkapınar',
      'Evka 4',
      'Evka 3',
      'Bornova',
      'Kayaşehri',
      'Şirinyer',
      'Buca',
      'Çağdaş',
      'Üçyol',
    ],
  },
];
